### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by scpeters** [ros/urdfdom_headers#20]
Is it possible to make a new 0.4.0 release of this and urdfdom?

**Comment by scpeters** [comment]
The only open pull request now is #3 and it is not ready to be merged. I think we are ready for a 0.4.0 release.

**Comment by scpeters** [comment]
https://github.com/ros/urdfdom_headers/releases/tag/0.4.0

**Comment by scpeters** [comment]
@j-rivero I'm going to try to release console_bridge and urdfdom as well. Hopefully they can all make it to debian together.

**Comment by j-rivero** [comment]
> @j-rivero I'm going to try to release console_bridge and urdfdom as well. Hopefully they can all make it to debian together.

ACK.
