### ISSUE TITLE
0.4.1 version

### ISSUE THREAD

**Issue by jpgr87** [ros/urdfdom_headers#28]
It looks like 0.4.1 was released with version 0.4.0 in CMakeLists.txt.  Was this just an oversight?

**Comment by scpeters** [comment]
yes, that was an oversight, I've bumped the minor number on the master branch and started a draft for a 0.4.2 release

* https://github.com/ros/urdfdom_headers/releases/tag/untagged-c01ec60a0ee437aacf0d
* https://github.com/ros/urdfdom/releases/tag/untagged-ad52f8650f859f0792c3

**Comment by jpgr87** [comment]
OK I thought so.  I'll correct the version number in the Fedora package.

**Comment by sloretz** [comment]
Looks like this is resolved. Feel free to reopen if that's not the case.
