### ISSUE TITLE
Parsing of colors should not be locale dependent

### ISSUE THREAD

**Issue by simonschmeisser** [ros/urdfdom_headers#46]
https://github.com/ros/urdfdom_headers/blob/e7e0972a4617b8a5df7a274ea3ba3b92e3895a35/urdf_model/include/urdf_model/color.h#L76

uses `std::stof` which is locale dependent and will truncate floats to ints if the decimal seperator does not match

this is the same issue as addressed in #45 but not included there as neither I nor anybody else looked closely enough ...

**Comment by gavanderhoorn** [comment]
Would it be an idea to do an audit of the relevant packages for use of `std::stof` and similar methods and replace them where appropriate?

I believe you've (@simonschmeisser) have proposed a similar change (moving away from locale-affected methods) for MoveIt. Seeing as this could be a cross-package issue: perhaps refactor this all out into a separate package and use that everywhere?

**Comment by simonschmeisser** [comment]
The change in MoveIt! is because boost::lexical_cast is inconsistent in itself (ie `boost::lexical_cast<double>(boost::lexical_cast<std::string>(0.1))` will throw an exception)

but yes, it's going to be a recurrent theme as more packages discover the nice (and totally inconsistent) features in C++ 11 and want to move away from boost::lexical_cast<double> (which is not locale dependent ...)

also note that the word "locale" does not appear a single time in boost::lexical_cast documentation so they might switch to using something broken in future releases ...
