### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by hubernikus** [ros/urdfdom_headers#75]
Can (and if yes, how is) this library be installed without ROS?

**Comment by traversaro** [comment]
Yes, it is quite a standard C++ library using CMake as a build system, once you made sure the dependencies for it are available in the environment, you can install it with: 
~~~
cd urdfdom_headers
mkdir build
cd build
ccmake -DCMAKE_INSTALL_PREFIX=<install_prefix> ..
cmake --build . --target install
~~~

**Comment by hubernikus** [comment]
Thanks a lot!
