### ISSUE TITLE
should this be deprecated in indigo?

### ISSUE THREAD

**Issue by jbohren** [ros/urdfdom_headers#9]

**Comment by vrabaud** [comment]
why ?

**Comment by jbohren** [comment]
Because there's nothing there: https://github.com/ros/urdfdom_headers/tree/indigo-devel

**Comment by jacquelinekay** [comment]
The library is still used in indigo, it's just not a catkin package. The `indigo_devel` branch is a passthrough package that references the system debian package that this source compiles to.
